### PR TITLE
feat: Buttons

### PR DESCRIPTION
**Pull request by neli-rashkova**
### Type of Change

- [ ] New Feature

### Description

Created a reusable `Button` component with 12 different variants. Any button label/text, icons, or elements can be added into this component as it uses slots. Additional styling can be added to the button for customizable purposes. Includes storybook component.
Props include:

- "variant": ('primary', 'primaryOutline', 'secondary', 'secondaryOutline', 'info', 'infoOutline', 'success', 'successOutline', 'warning', 'warningOutline', 'danger', 'dangerOutline'), default: 'primary'
- "disabled": (true / false)
- "size": ('small', 'medium', 'large'), default: 'medium'
- "btnType": ('button', 'submit', 'reset'), default: 'button'
- "onClick"

### Testing Instructions

- Open terminal and run "npm run dev" so application opens in browser with local host
- Import `Button` component and add to the template (`<Button></Button>`)
- For props: passing variant changes the styles of the button, if no variant is passed default style is applied; passing size changes the size of the button, the default size is medium; passing btnType specifies the type of button, default is button, passing disabled makes button disabled and disabled styling is applied

### Testing Instructions Storybook

- Open terminal and run "npm run storybook" to open in the browser
- Open storybook in browse "http://localhost:6006/" or "http://localhost:6007/"
- Select variant, size, and disabled/ not disabled 

#### Different Button variants
Screenshot 2023-05-18 at 3 07 16 PM

#### Using the `Button` component in template example:
Screenshot 2023-05-18 at 5 00 09 PM

#### Storybook - some themes are shown in screenshots
Screenshot 2023-05-18 at 4 46 27 PM
Screenshot 2023-05-18 at 4 46 55 PM
Screenshot 2023-05-18 at 4 48 22 PM

### CODE REVIEW

**Comment by roxanehe** [comment]
well done!!

**Review by YoussefLaunchUp — APPROVED** [review]
Great work!

**Comment by YoussefLaunchUp** [comment]
@neli-rashkova Make sure to update the PR title to follow conventional commits

**Review by roxanehe — APPROVED** [review]
ready to merge!

**Pull request merged**
