### PR TITLE
Chore: Clean & Refactor Files

### PR DESCRIPTION
**Pull request by kelvin3127**
### Type of Change
- [ ] Refactoring

### Description
Removed Boilerplate files and left it as a simple one page Vue app
Changed Title
-Removed Boilerplate Components
-Removed Boilerplate Assets
-Removed Views Folder
-Removed Stores Folder
-Removed Stories Folder
-Removed Router Folder

Branched off from PR ckelvin3127/das-6-set-up-story-book 

### Testing Instructions
Run using -npm run dev- to see changes made to app

### CODE REVIEW

**Review by YoussefLaunchUp — CHANGES_REQUESTED** [review]
Looks like this is has been branched from the other PR's branch meaning that this cannot get merged until the other one gets merged. Whenever this is the case make sure to add this info in the PR description.

**Comment by kelvin3127** [comment]
> Looks like this is has been branched from the other PR's branch meaning that this cannot get merged until the other one gets merged. Whenever this is the case make sure to add this info in the PR description.

Updated PR description to add branch off

**Review by YoussefLaunchUp — APPROVED** [review]
Good work

**Review by YoussefLaunchUp — APPROVED** [review]

**Comment by simsung1** [comment]
Looks great to me!

**Review by simsung1 — APPROVED** [review]
Great job!!

**Pull request merged**
